# Generated by Django 4.1.7 on 2023-11-11 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0002_postapp_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='postapp',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
