# Generated by Django 4.1.7 on 2023-12-28 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0003_postapp_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='postapp',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='投稿画像'),
        ),
    ]
